name: Issue due-date labels
on:
  schedule:
    - cron: '0 * * * *'   # hourly
  workflow_dispatch: #run it manually

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - uses: alexleventer/github-issue-due-dates-action@v2
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          upcoming-labels: |
            - days: 3
              label: 'Due in 3 days'
            - days: 14
              label: 'Due in 2 weeks'
            - days: 30
              label: 'Due in a month'
